var appConstants = {
  FRESHFINDER_MARKET_ADDRESS: "FRESHFINDER_MARKET_ADDRESS",
  FRESHFINDER_MARKET_PAYMENT_TYPES: "FRESHFINDER_MARKET_PAYMENT_TYPES",
  FRESHFINDER_MARKET_PRODUCTS: "FRESHFINDER_MARKET_PRODUCTS",
  FRESHFINDER_MARKET_SEASONS: "FRESHFINDER_MARKET_SEASONS"
  FRESHFINDER_CHANGE_MARKET: "FRESHFINDER_CHANGE_MARKET",
};

module.exports = appConstants;
